apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calculation-ui
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: calculation-ui
  targetCPUUtilizationPercentage: 60
  # Need to add requests per second metric to scale the pods based on requests