apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: calculation-api
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: calculation-api
  targetCPUUtilizationPercentage: 60