kind: Service
apiVersion: v1
metadata:
  name: calculation-ui
spec:
  type: NodePort
  selector:
    app: calculation-ui
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
---
kind: Service
apiVersion: v1
metadata:
  name: calculation-api
spec:
  type: NodePort
  selector:
    app: calculation-api
  ports:
  - protocol: TCP
    port: 30001
    nodePort: 30001
